# Generated by Django 4.2.30 on 2026-05-17 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trivias', '0001_initial'),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='triviaparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='triviaanswer',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='trivias.triviaparticipant'),
        ),
        migrations.AddField(
            model_name='triviaanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question'),
        ),
        migrations.AddField(
            model_name='triviaanswer',
            name='selected_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.answer'),
        ),
        migrations.AddField(
            model_name='trivia',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_trivias', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trivia',
            name='participants',
            field=models.ManyToManyField(related_name='trivias', through='trivias.TriviaParticipant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trivia',
            name='questions',
            field=models.ManyToManyField(to='questions.question'),
        ),
        migrations.AlterUniqueTogether(
            name='triviaparticipant',
            unique_together={('trivia', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='triviaanswer',
            unique_together={('participant', 'question')},
        ),
    ]
